[package]
name = "backblaze-b2"
version = "0.1.5"
authors = ["Alice Ryhl <alice@ryhl.io>"]
description = "Can send api requests to the backblaze b2 api."
repository = "https://github.com/Darksonn/backblaze-b2-rs"
readme = "README.md"
keywords = ["backblaze", "b2", "backup", "api"]
categories = ["api-bindings"]
license = "MIT"
exclude = ["credentials.txt"]

[dependencies]
base64 = "~0.5.0"
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
hyper = "0.10.10"

[dev-dependencies]
rand = "0.3"
sha1 = "0.2.0"
hyper-native-tls = "0.2.2"
